#ifndef CONFIG_H
#define CONFIG_H

#define WEE_APPLICATION_NAME "WAVExplorer"
#define WEE_PLAYER_LEVEL_DEFAULT 0.5
#define WEE_SCANNER_WIDTH 1600
#define WEE_SCANNER_HEIGHT 120
#define WEE_SCANNER_LINE_ONLY_DEFAULT false
#define WEE_SCANNER_FOREGROUND_DEFAULT QColor("#2d89ef")

#define WEE_HELPER_SLEEP_TIME 100

#endif // CONFIG_H
