#ifndef SOUND_CONFIG_H
#define SOUND_CONFIG_H

#define SOUND_PROCESSOR_COMMAND_BUS_SIZE 64
#define SOUND_PROCESSOR_SIGNAL_BUS_SIZE 256
#define SOUND_PROCESSOR_PARAMETER_BUS_SIZE 128

#define SOUND_PROCESSOR_METER_PASS_FRAMES 2000

#endif // CONFIG_H
