#ifndef SOUND_CONFIG_H
#define SOUND_CONFIG_H

#define SOUND_PROCESSOR_BUS_SIZE 64
#define SOUND_PROCESSOR_BUS_HOLD_FACTOR 16

#define SOUND_PROCESSOR_METER_PASS_FRAMES 2000
#define SOUND_MIXER_MAX_SOURCES 1024
#define SOUND_MIXER_BUFFER_SIZE 4096

#define SOUND_DITHER
#define SOUND_NOISE_SHAPE
#define SOUND_USE_LONG_DOUBLE

#define SOUND_DEFAULT_INT_BITS 32
#define SOUND_DEFAULT_FLOAT_BITS 64

#endif // CONFIG_H
