#ifndef SOUND_CONFIG_H
#define SOUND_CONFIG_H

#define SOUND_PROCESSOR_SIGNAL_BUS_SIZE 1024
#define SOUND_PROCESSOR_PARAMETER_BUS_SIZE 1024
#define SOUND_PROCESSOR_SIGNAL_BUS_HOLDED_SIZE 4096

#define SOUND_PROCESSOR_METER_PASS_FRAMES 2000

#endif // CONFIG_H
